name: validate
on:
  push:
    branches-ignore: [ 'main' ]

jobs:

  TypeCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: cache-dependencies
        with:
          python-version: '3.11'
          cache: 'pipenv'
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pipenv install -d --deploy

      - name: Check types
        run: pipenv run check-types

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: cache-dependencies
        with:
          python-version: '3.11'
          cache: 'pipenv'
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pipenv install -d --deploy

      - name: Format
        run: pipenv run format

      - name: Lint
        run: pipenv run lint

      - name: Test
        run: pipenv run test

  Build_Package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            ARTIFACT_NAME: surfaid_namescan_mac
            SPEC_FILE: surfaid_namescan_mac.spec
            EXECUTABLE_FILE: surfaid_namescan
          - os: windows-latest
            ARTIFACT_NAME: surfaid_namescan_windows
            SPEC_FILE: surfaid_namescan_windows.spec
            EXECUTABLE_FILE: surfaid_namescan.exe

    needs: [TypeCheck, Test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: cache-dependencies
        with:
          python-version: '3.11'
          cache: 'pipenv'
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          pipenv install -d --deploy
          pipenv install pyinstaller

      - name: PyInstaller Windows
        run: pipenv run pyinstaller ${{ matrix.SPEC_FILE }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.ARTIFACT_NAME}}
          path: dist/${{matrix.EXECUTABLE_FILE}}